#! /bin/bash

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Anton Lokhmotov, anton@dividiti.com
#

echo "*** Current DDR frequency:"
/usr/local/k1tools/bin/k1-dt-tool --ddr-freq

echo "*** Min DDR frequency:"
echo "1066"

echo "*** Max DDR frequency:"
echo "1333"

echo "*** Available DDR frequencies:"
echo "1066 1333"
