#! /bin/bash

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Anton Lokhmotov, anton@dividiti.com
#

 cd "$(dirname "${BASH_SOURCE[0]}")"
 . ck-set-ddr-frequency 1066
